export const STATUS_LABELS = {draft_ready:"Anyagok elkészültek",new:"Új",needs_review:"Ellenőrzésre vár",checkout_pending:"Fizetés előkészítése",qualified:"Egyeztetve",awaiting_payment:"Fizetésre vár",paid:"Fizetve",in_production:"Készül",review:"Jóváhagyásra vár",completed:"Lezárt",cancelled:"Lemondva",researched:"Felkutatva",approved:"Jóváhagyva",contacted:"Megkeresve (kézi)",replied:"Válaszolt",won:"Ügyfél",do_not_contact:"Tiltólistán",sending:"Küldés folyamatban",send_unknown:"Bizonytalan küldés",draft:"Piszkozat",queued:"Sorban áll",sent:"Szolgáltató átvette",delivered:"Kézbesítve",bounced:"Visszapattant",failed:"Sikertelen",suppressed:"Küldés tiltva",planned:"Tervezett",active:"Aktív",paused:"Szüneteltetve",pending:"Várakozik",processing:"Folyamatban",done:"Kész",retry:"Újrapróbálás",blocked:"Blokkolva",plan_ready:"Terv elkészült",generating:"Generálás alatt",generation_failed:"Generálási hiba",awaiting_ai_configuration:"AI-beállításra vár",intake:"Feldolgozás alatt",waiting_customer:"Ügyféladatokra vár",ready:"Indításra kész",production:"Készül",resolved:"Lezárva",online:"Elérhető",down:"Nem elérhető",warning:"Figyelmeztetés",healthy:"Rendben",attention:"Figyelmet igényel"};
export const SOURCE_NAMES={production_copy_jobs:"AI-szövegek",booking_tenants:"Foglalási naptárak",internal_alerts:"Üzemeltetési jelzések",booking_notifications:"Foglalási értesítések",orders:"Rendelések",order_workflows:"Munkafolyamatok",customer_requests:"Ügyfélkérések",customer_notifications:"Ügyfélértesítések",maintenance_sites:"Karbantartás",operations_health:"Rendszerállapot",leads:"Leadek",commerce_tasks:"Automatizálás",payments:"Fizetések",production_jobs:"Gyártás",outreach_messages:"Hirdető e-mailek",campaigns:"Kampányok",expenses:"Költségek",outreach_research:"Kutatások",outreach_replies:"Válaszlevelek"};
export function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);}
export function safeUrl(value){try{const url=new URL(value);return ["https:","http:"].includes(url.protocol)?url.href:"";}catch{return "";}}
export function dateMs(value){if(value?.toMillis)return value.toMillis();if(value?.seconds!=null)return Number(value.seconds)*1000;if(value==null||value==="")return NaN;return typeof value==="number"?value:new Date(value).getTime();}
export function dayKey(value){if(typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const ms=dateMs(value);if(!Number.isFinite(ms))return "";const parts=Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Budapest",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(ms).map(p=>[p.type,p.value]));return `${parts.year}-${parts.month}-${parts.day}`;}
export function inPeriod(value,from,to){const day=dayKey(value);return (!from&&!to)||Boolean(day&&(!from||day>=from)&&(!to||day<=to));}
export function money(value,currency="HUF"){return new Intl.NumberFormat("hu-HU",{style:"currency",currency,maximumFractionDigits:currency==="HUF"?0:2}).format(Number(value)||0);}
export function providerSent(record){return record.source==="provider"&&Boolean(record.providerMessageId)&&Boolean(record.sentAt)&&["sent","delivered","replied","bounced"].includes(record.status);}
export function summarize(data,from="",to=""){
  const orders=(data.orders||[]).filter(r=>inPeriod(r.createdAt,from,to));
  const messages=(data.outreach_messages||[]).filter(r=>inPeriod(r.sentAt||r.createdAt,from,to));
  const expenses=(data.expenses||[]).filter(r=>inPeriod(r.incurredOn,from,to));
  const payments=(data.payments||[]).filter(r=>r.status==="paid"&&r.livemode===true&&inPeriod(r.createdAt,from,to));
  const paidValue=payments.reduce((sum,p)=>sum+(Array.isArray(p.products)?p.products.reduce((s,item)=>s+(Number.isSafeInteger(item.price)&&item.price>=0?item.price:0),0):0),0);
  const costs={HUF:0,EUR:0,USD:0};for(const row of expenses)if(Object.hasOwn(costs,row.currency)&&Number.isSafeInteger(row.amountMinor)&&row.amountMinor>0)costs[row.currency]+=row.amountMinor/100;
  return {orders:orders.length,active:orders.filter(r=>["paid","in_production","review"].includes(r.status)).length,sent:messages.filter(providerSent).length,replied:messages.filter(r=>providerSent(r)&&r.status==="replied").length,attention:(data.commerce_tasks||[]).filter(r=>["blocked","needs_review","retry"].includes(r.status)).length,paidValue,costs,expenses,ordersList:orders,messages};
}
export function parseAmount(value,currency,allowZero=false){const text=String(value??"").trim().replace(",",".");if(!["HUF","EUR","USD"].includes(currency)||!/^\d{1,9}(?:\.\d{1,2})?$/.test(text))throw new Error("Adj meg érvényes összeget, legfeljebb két tizedessel.");const amount=Math.round(Number(text)*100);if(!Number.isSafeInteger(amount)||amount>10000000000||amount<(allowZero?0:1))throw new Error("Az összeg kívül esik a megengedett tartományon.");return amount;}
export function validateCampaign(raw){const name=String(raw.name||"").trim(),platform=String(raw.platform||""),destination=safeUrl(raw.destination),creative=String(raw.creative||"").trim(),budgetMinor=parseAmount(raw.budget,"HUF",true);if(name.length<2||name.length>120||!["Meta Ads","Google Ads","TikTok Ads","LinkedIn Ads","E-mail","Egyéb"].includes(platform)||!destination||destination.length>500||creative.length>2000||!["planned","active","paused","completed"].includes(raw.status))throw new Error("Ellenőrizd a kampány nevét, csatornáját és céloldalát.");return {name,platform,destination,creative,budgetMinor,currency:"HUF",budgetPeriod:"monthly",status:raw.status,source:"manual"};}
export function validateExpense(raw,campaignIds=[]){const label=String(raw.label||"").trim(),currency=String(raw.currency||""),amountMinor=parseAmount(raw.amount,currency),incurredOn=String(raw.incurredOn||""),campaignId=String(raw.campaignId||"");if(label.length<2||label.length>120||!/^20\d{2}-\d{2}-\d{2}$/.test(incurredOn)||!Number.isFinite(Date.parse(incurredOn))||new Date(incurredOn).toISOString().slice(0,10)!==incurredOn||!["advertising","hosting","ai","invoicing","email","other"].includes(raw.category)||(campaignId&&!campaignIds.includes(campaignId)))throw new Error("Ellenőrizd a költség megnevezését, dátumát és kampányát.");return {label,amountMinor,currency,incurredOn,category:raw.category,campaignId,source:"manual"};}
export function csv(rows){return "\ufeff"+rows.map(row=>row.map(value=>{let cell=String(value??"");if(/^[\s]*[=+@-]/.test(cell))cell="'"+cell;return '"'+cell.replace(/"/g,'""')+'"';}).join(";")).join("\r\n");}
export function outreachReady(row){return row.status==="draft"&&row.qualification?.version===2&&["no_website","website_refresh"].includes(row.qualification.targetMode)&&Boolean(row.emailVerifiedAt);}
export function outreachBlockedReason(row){
  if(row.status!=="draft")return "Ez nem küldésre váró piszkozat.";
  if(row.qualification?.version!==2||!["no_website","website_refresh"].includes(row.qualification?.targetMode))return "Régi vagy nem minősített jelölt. Az új kutatás nem hagyta jóvá; ebből a listából nem küldhető.";
  if(!row.emailVerifiedAt)return "Az e-mail-cím nyilvános forrása nincs ellenőrizve.";
  return "";
}
