export const ZONE='Europe/Budapest';
export const labels={confirmed:'Visszaigazolt',cancelled:'Lemondva',completed:'Teljesítve',no_show:'Nem jelent meg'};
export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money=value=>new Intl.NumberFormat('hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(value);
export const time=value=>new Intl.DateTimeFormat('hu-HU',{timeZone:ZONE,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value));
export const prettyDate=value=>new Intl.DateTimeFormat('hu-HU',{timeZone:ZONE,month:'long',day:'numeric',weekday:'long'}).format(new Date(value+'T12:00:00Z'));
export function dayKey(value=Date.now()){const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(value).map(p=>[p.type,p.value]));return `${p.year}-${p.month}-${p.day}`;}
export function addDays(date,n){if(!/^20\d{2}-\d{2}-\d{2}$/.test(date)||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)throw Error('Érvénytelen dátum.');return new Date(Date.parse(date+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);}
export function secret(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');}
export function cancellationFragment(value){const p=new URLSearchParams(value.replace(/^#/,''));const tenantId=p.get('tenant'),bookingId=p.get('booking'),cancellationToken=p.get('token');return /^[a-zA-Z0-9_-]{1,80}$/.test(tenantId||'')&&/^[a-zA-Z0-9_-]{1,80}$/.test(bookingId||'')&&/^[a-f0-9]{64}$/.test(cancellationToken||'')?{tenantId,bookingId,cancellationToken}:null;}
export function metrics(rows){return {count:rows.filter(r=>r.status==='confirmed').length,completed:rows.filter(r=>r.status==='completed').length,scheduledValue:rows.filter(r=>r.status==='confirmed').reduce((sum,r)=>sum+r.service.priceHuf,0)};}
function reject(message,code='failed-precondition'){throw Object.assign(new Error(message),{code});}
const instantCache=new Map();
function localInstant(date,hour,minute=0){const key=`${date}:${hour}:${minute}`;if(instantCache.has(key))return instantCache.get(key);const base=Date.parse(date+'T00:00:00Z');for(let offset=-3;offset<=-1;offset++){const t=base+(hour+offset)*3600000+minute*60000;if(dayKey(t)===date&&time(t)===`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`){const result=new Date(t).toISOString();instantCache.set(key,result);return result;}}reject('Ez a bemutató-időpont nem használható.');}
// Deliberately ephemeral, synthetic sandbox. Never imported by the live adapter.
// No customer data, storage, email, network or external account changes.
export function createDemoApi(now=Date.now()){
  const today=dayKey(now),tomorrow=addDays(today,1),rows=new Map(),requests=new Map(),operations=new Map();
  const settings={businessName:'OVEXI • Minta Szolgáltató',privacyUrl:'https://ovexi.hu/adatkezeles',horizonDays:60,minNoticeMinutes:0,timeZone:ZONE,services:[{id:'consultation',name:'Személyes konzultáció',durationMinutes:30,priceHuf:6000,active:true},{id:'service',name:'Egyórás szolgáltatás',durationMinutes:60,priceHuf:12000,active:true}]};
  function slots(serviceId,date,exclude){addDays(date,0);const s=settings.services.find(s=>s.id===serviceId);if(!s)reject('Nincs ilyen szolgáltatás.');if(date<today||date>addDays(today,60))return [];
    const result=[];for(let m=9*60;m+s.durationMinutes<=17*60;m+=30){if(m<13*60&&m+s.durationMinutes>12*60)continue;const start=localInstant(date,Math.floor(m/60),m%60),end=new Date(Date.parse(start)+s.durationMinutes*60000).toISOString();if(Date.parse(start)<now)continue;if([...rows.values()].some(r=>r.bookingId!==exclude&&r.status!=='cancelled'&&r.start<end&&start<r.end))continue;result.push({start,end});}return result;
  }
  function insert(bookingId,date,hour,serviceIndex,name){const service=settings.services[serviceIndex],start=localInstant(date,hour);rows.set(bookingId,{bookingId,date,start,end:new Date(Date.parse(start)+service.durationMinutes*60000).toISOString(),status:'confirmed',revision:1,service,name,email:'teszt@example.invalid',notificationStatus:'demo_no_email',timeZone:ZONE});}
  insert('demo-tomorrow',tomorrow,10,1,'Minta Vendég');insert('demo-yesterday',addDays(today,-1),10,0,'Korábbi Minta Vendég');
  const copy=r=>structuredClone(r);
  return {demo:true,defaultDate:tomorrow,
    async publicConfig(){return copy(settings);},async availability({serviceId,date}){return {slots:slots(serviceId,date),timeZone:ZONE};},
    async createBooking(input){const fingerprint=JSON.stringify(input);if(requests.has(input.requestId)){const previous=requests.get(input.requestId);if(previous.fingerprint!==fingerprint)reject('A kérés megváltozott.');return copy(rows.get(previous.id));}if(input.name!=='Próba Vendég'||input.email!=='proba@example.invalid'||input.privacyAccepted!==true)reject('A bemutatóban csak a megadott próbaadatok használhatók.','invalid-argument');const slot=slots(input.serviceId,input.date).find(s=>s.start===input.start);if(!slot)reject('Az időpont már nem foglalható.','already-exists');const bookingId=crypto.randomUUID(),row={bookingId,date:input.date,...slot,status:'confirmed',revision:1,service:copy(settings.services.find(s=>s.id===input.serviceId)),name:input.name,email:input.email,notificationStatus:'demo_no_email',timeZone:ZONE,cancellationToken:input.cancellationToken};rows.set(bookingId,row);requests.set(input.requestId,{fingerprint,id:bookingId});return copy(row);},
    async guestStatus(input){const row=rows.get(input.bookingId);if(!row||row.cancellationToken!==input.cancellationToken)reject('Érvénytelen hozzáférés.','not-found');const {cancellationToken,name,email,...result}=row;return copy(result);},
    async cancelBooking(input){const row=rows.get(input.bookingId);if(!row||row.cancellationToken!==input.cancellationToken)reject('Érvénytelen lemondás.','not-found');if(row.status==='cancelled')return {bookingId:row.bookingId,status:'cancelled'};if(row.status!=='confirmed'||Date.parse(row.start)<=now)reject('Ez a foglalás már nem mondható le.');row.status='cancelled';row.revision++;return {bookingId:row.bookingId,status:row.status};},
    async ownerDay({date}){return {bookings:[...rows.values()].filter(r=>r.date===date).map(({cancellationToken,...r})=>copy(r)).sort((a,b)=>a.start.localeCompare(b.start))};},
    async ownerStatus(input){return mutate(input,false);},async ownerMove(input){return mutate(input,true);},
    async ownerMoveSlots(input){const row=rows.get(input.bookingId);if(!row||row.status!=='confirmed'||Date.parse(row.start)<=now)reject('Ez a foglalás nem helyezhető át.');return {slots:slots(row.service.id,input.date,row.bookingId),timeZone:ZONE};},
    async login(){},async logout(){},isOwnerSignedIn:()=>true
  };
  function mutate(input,move){const fingerprint=JSON.stringify(input);if(operations.has(input.requestId)){const prior=operations.get(input.requestId);if(prior.fingerprint!==fingerprint)reject('A módosítás megváltozott.');return copy(prior.result);}const row=rows.get(input.bookingId);if(!row||row.revision!==input.expectedRevision||row.status!=='confirmed')reject('A foglalás megváltozott. Frissítsd a naptárat.');if(move){if(Date.parse(row.start)<=now)reject('Megkezdett időpont nem helyezhető át.');const slot=slots(row.service.id,input.date,row.bookingId).find(s=>s.start===input.start);if(!slot)reject('Ez az időpont nem foglalható.','already-exists');Object.assign(row,slot,{date:input.date});}else{if(!['completed','no_show','cancelled'].includes(input.status))reject('Érvénytelen státusz.');if(input.status==='completed'&&Date.parse(row.end)>now||input.status==='no_show'&&Date.parse(row.start)>now||input.status==='cancelled'&&Date.parse(row.start)<=now)reject('Ez a státusz ennél az időpontnál nem használható.');row.status=input.status;}row.revision++;const {cancellationToken,...result}=row;operations.set(input.requestId,{fingerprint,result:copy(result)});return copy(result);}
}
