import {createDemoApi,escapeHtml as e,money,time,prettyDate,dayKey,addDays,secret,labels,metrics,cancellationFragment} from './booking-model.js?v=20260902-2';
import {liveBookingApi} from './booking-api.js?v=20260902-2';
import {safeStorage} from './customer-model.js?v=20260902-1';
const store=safeStorage(()=>sessionStorage);
const $=id=>document.getElementById(id),query=new URLSearchParams(location.search),demo=query.get('demo')==='1';
let cancelRequest=cancellationFragment(location.hash);
const cancelStateKey='ovexi-booking-cancel:'+ (cancelRequest?.tenantId||query.get('tenant')||'');
if(!demo&&cancelRequest){store.set(cancelStateKey,JSON.stringify({request:cancelRequest,expiresAt:Date.now()+86400000}));query.set('tenant',cancelRequest.tenantId);query.set('cancel','1');history.replaceState(null,'',location.pathname+'?'+query);}
else if(!demo&&query.get('cancel')==='1'){try{const state=JSON.parse(store.get(cancelStateKey)||'null');if(state?.expiresAt>Date.now())cancelRequest=state.request;}catch{}}

if(location.hash)history.replaceState(null,'',location.pathname+location.search);
let api,settings,tenantId=query.get('tenant')||'',selectedSlot='',slotRows=[],saved=null,pending=null,busy=false,slotEpoch=0,dayEpoch=0,ownerRows=[],moveTarget=null;
const notificationLabel=value=>({queued:'küldésre vár',pending:'küldésre vár',sent:'a levelezőszerver átvette',disabled:'nincs bekapcsolva',send_unknown:'kézbesítése ellenőrzendő',failed:'sikertelen',retry:'újrapróbálásra vár',blocked:'beállításra vár'}[value]||'ellenőrizendő');
const ownerRequests=new Map();
const guestKey=()=> 'ovexi-booking:'+tenantId;
const ownerKey=()=> 'ovexi-booking-owner:'+tenantId+':'+(api?.identity?.()||'demo');
function persist(){if(!demo&&!store.set(guestKey(),JSON.stringify({pending,saved,expiresAt:Date.now()+86400000})))message('globalStatus','A böngésző nem engedi a munkamenet mentését. Őrizd meg a lemondási linket.');}
function restore(){if(demo)return;try{const state=JSON.parse(store.get(guestKey())||'null');if(state?.expiresAt>Date.now()&&state.pending?.tenantId===tenantId){pending=state.pending;saved=state.saved;}}catch{}}
function displaySaved(){if(!saved)return;$('serviceSelect').value=pending.serviceId;$('bookingDate').value=pending.date;selectedSlot=pending.start;$('guestName').value=pending.name;$('guestEmail').value=pending.email;summary();$('bookingResult').hidden=false;message('resultTitle',saved.status==='cancelled'?'Foglalás lemondva':'Időpont rögzítve');message('resultDetails',saved.service.name+' · '+prettyDate(saved.date)+', '+time(saved.start)+'–'+time(saved.end));message('notificationNote',demo?'Próbaadat; nincs e-mail.':'Az értesítés állapota: '+notificationLabel(saved.notificationStatus)+'. A foglalás nem fizetési visszaigazolás.');$('cancelBooking').disabled=saved.status!=='confirmed';formLock(true);}

const message=(id,value)=>{$(id).textContent=value;};
function safeError(error){return String(error?.message||'A művelet eredménye nem igazolható. Frissíts, mielőtt új műveletet indítasz.').slice(0,350);}
function service(){return settings.services.find(s=>s.id===$('serviceSelect').value);}
function formLock(locked){for(const el of $('bookingForm').elements)el.disabled=locked;$('bookButton').disabled=locked||!selectedSlot;}
function summary(){const s=service();message('summaryService',s?.name||'Válassz szolgáltatást');message('summaryDate',$('bookingDate').value?prettyDate($('bookingDate').value):'—');message('summaryTime',selectedSlot?time(selectedSlot):'—');message('summaryDuration',s?`${s.durationMinutes} perc`:'—');message('summaryPrice',s?money(s.priceHuf):'—');}
async function loadSlots(){if(!api||!settings||saved||pending)return;const ticket=++slotEpoch;selectedSlot='';slotRows=[];summary();$('bookButton').disabled=true;if(!$('bookingDate').value){$('slots').textContent='Válassz egy napot.';return;}$('slots').textContent='Szabad időpontok lekérése…';
  try{const result=await api.availability({tenantId,serviceId:$('serviceSelect').value,date:$('bookingDate').value});if(ticket!==slotEpoch)return;slotRows=result.slots;$('slots').innerHTML=slotRows.map(s=>`<label><input type="radio" name="slot" value="${e(s.start)}" required><span>${e(time(s.start))}</span></label>`).join('')||'<p class="muted">Erre a napra nincs szabad időpont. Válassz másik napot vagy szolgáltatást.</p>';}
  catch(error){if(ticket===slotEpoch){$('slots').textContent='Az időpontok nem tölthetők be.';message('bookingStatus',safeError(error));}}
}
async function showOwner(){if(!api)return;$('guestPanel').hidden=true;$('ownerPanel').hidden=false;$('ownerTab').setAttribute('aria-pressed','true');$('guestTab').setAttribute('aria-pressed','false');$('ownerLogin').hidden=api.isOwnerSignedIn();$('ownerLogout').hidden=demo||!api.isOwnerSignedIn();await loadDay();}
function showGuest(){if(!api)return;$('ownerPanel').hidden=true;$('guestPanel').hidden=false;$('ownerTab').setAttribute('aria-pressed','false');$('guestTab').setAttribute('aria-pressed','true');}
async function loadDay(){if(!api)return;const ticket=++dayEpoch;$('dayBookings').textContent='Naptár betöltése…';$('dayMetrics').innerHTML='';ownerRows=[];moveTarget=null;
  if(!api.isOwnerSignedIn()){$('dayBookings').textContent='A vendégek adatai csak a naptár tulajdonosának belépése után érhetők el.';return;}
  try{const result=await api.ownerDay({tenantId,date:$('ownerDate').value});if(ticket!==dayEpoch)return;ownerRows=result.bookings;message('ownerStatus','');renderDay();if(!demo&&store.get(ownerKey()))$('dayBookings').insertAdjacentHTML('beforeend','<button type="button" data-resume-owner>Félbemaradt módosítás ellenőrzése</button>');}catch(error){if(ticket===dayEpoch){$('dayBookings').textContent='A napi naptár nem érhető el.';message('ownerStatus',safeError(error));}}
}
function renderDay(){const m=metrics(ownerRows);$('dayMetrics').innerHTML=[[m.count,'Várható foglalás'],[m.completed,'Teljesített alkalom'],[money(m.scheduledValue),'Tervezett szolgáltatási érték · nem bevétel']].map(([value,label])=>`<div class="metric"><strong>${e(value)}</strong><span>${e(label)}</span></div>`).join('');
  $('dayBookings').innerHTML=ownerRows.map(r=>{const active=r.status==='confirmed',future=Date.parse(r.start)>Date.now();return `<article class="appointment"><div><time>${e(time(r.start))}</time><p class="muted">${e(time(r.end))}-ig</p></div><div><h3>${e(r.name)}</h3><p>${e(r.service.name)} · ${money(r.service.priceHuf)}</p><p>${e(r.email)}</p><span class="badge">${e(labels[r.status]||r.status)}</span><p class="muted">${demo?'Próbaadat · nincs levélküldés':r.notificationStatus==='not_implemented'?'E-mail-értesítés még nincs bekötve':`Értesítés: ${e(notificationLabel(r.notificationStatus))}`}</p></div><div class="actions">${active?`<button class="secondary" type="button" data-move="${e(r.bookingId)}" ${!future?'disabled':''}>Áthelyezés</button><button class="secondary" type="button" data-status="cancelled" data-booking="${e(r.bookingId)}" ${!future?'disabled':''}>Lemondás</button><button class="secondary" type="button" data-status="completed" data-booking="${e(r.bookingId)}" ${Date.parse(r.end)>Date.now()?'disabled':''}>Teljesítve</button><button class="secondary" type="button" data-status="no_show" data-booking="${e(r.bookingId)}" ${future?'disabled':''}>Nem jelent meg</button>`:''}</div></article>`;}).join('')||'<p class="empty">Erre a napra nincs foglalás.</p>';
  if(demo)$('dayBookings').insertAdjacentHTML('beforeend','<p class="muted">A tegnapi naphoz is tartozik egy próbaidőpont: ott kipróbálhatod a „Teljesítve” és „Nem jelent meg” státuszt.</p>');
}
function ownerRequest(row,action,values={}){const key=JSON.stringify([row.bookingId,row.revision,action,values]);if(!ownerRequests.has(key))ownerRequests.set(key,{tenantId,bookingId:row.bookingId,expectedRevision:row.revision,requestId:crypto.randomUUID(),...values});return ownerRequests.get(key);}
async function ownerAction(row,action,values){if(busy)return;
  let original;try{original=!demo?JSON.parse(store.get(ownerKey())||'null'):null;}catch{}
  if(original&&action!=='resume'){message('ownerStatus','Előbb ellenőrizd a félbemaradt módosítást az alábbi gombbal.');return;}if(!original&&!confirm(action==='ownerMove'?'Áthelyezed a foglalást a kiválasztott időpontra?':'Megerősíted: '+labels[values.status]+'?'))return;
  const job=original||{action,payload:ownerRequest(row,action,values)};if(!demo)store.set(ownerKey(),JSON.stringify(job));busy=true;message('ownerStatus','Mentés folyamatban…');
  try{await api[job.action](job.payload);if(!demo)store.remove(ownerKey());message('ownerStatus',demo?'Próbamódosítás rögzítve.':'Módosítás rögzítve. Az értesítés állapota a naptárban követhető.');await loadDay();if(!saved)await loadSlots();}
  catch(error){if(['invalid-argument','already-exists','failed-precondition','not-found','permission-denied'].some(c=>error.code===c||error.code==='functions/'+c)){if(!demo)store.remove(ownerKey());}message('ownerStatus',safeError(error)+' A korábbi kérés a következő mentéskor újraellenőrizhető.');}
  finally{busy=false;}
}
$('guestTab').addEventListener('click',showGuest);$('ownerTab').addEventListener('click',showOwner);
for(const id of ['serviceSelect','bookingDate'])$(id).addEventListener('change',()=>{message('bookingStatus','');loadSlots();});
$('slots').addEventListener('change',event=>{if(!slotRows.some(s=>s.start===event.target.value))return;selectedSlot=event.target.value;$('bookButton').disabled=false;summary();});
$('bookingForm').addEventListener('submit',async event=>{event.preventDefault();if(busy||saved||!api)return;if(!pending){if(!selectedSlot)return;pending={tenantId,serviceId:service().id,date:$('bookingDate').value,start:selectedSlot,name:$('guestName').value.trim(),email:$('guestEmail').value.trim(),privacyAccepted:$('privacyAccepted').checked,requestId:crypto.randomUUID(),cancellationToken:secret()};persist();}busy=true;formLock(true);message('bookingStatus','Foglalás rögzítése…');
  try{saved=await api.createBooking(pending);persist();$('bookingResult').hidden=false;message('resultTitle',saved.status==='cancelled'?'Ez a foglalás már le lett mondva':demo?'Próbafoglalás elkészült':'Időpont rögzítve');message('resultDetails',`${saved.service.name} · ${prettyDate(saved.date)}, ${time(saved.start)}–${time(saved.end)}`);message('notificationNote',demo?'Ez nem valódi foglalás. E-mailt nem küldtünk. Frissítéskor a próbaadatok elvesznek.':'Az értesítés állapota: '+notificationLabel(saved.notificationStatus)+'. Mentsd el a lemondási linket; fizetés nem történt.');$('cancelBooking').disabled=saved.status!=='confirmed';message('bookingStatus','');$('bookingResult').scrollIntoView({block:'center',behavior:'smooth'});}
  catch(error){const definitive=['invalid-argument','already-exists','not-found','failed-precondition','permission-denied','resource-exhausted'].some(code=>error.code===code||error.code===`functions/${code}`);message('bookingStatus',safeError(error)+(definitive?'':' Az eredmény bizonytalan. A gomb ugyanazt a kérést próbálja újra; ne nyiss új foglalást.'));if(definitive){pending=null;persist();formLock(false);await loadSlots();}else{$('bookButton').disabled=false;$('bookButton').textContent='Ugyanazon foglalás újraellenőrzése';}}
  finally{busy=false;}
});
$('cancelBooking').addEventListener('click',async()=>{if(busy||!saved||!pending||!confirm('Biztosan lemondod ezt az időpontot?'))return;busy=true;$('cancelBooking').disabled=true;try{await api.cancelBooking({tenantId,bookingId:saved.bookingId,cancellationToken:pending.cancellationToken});saved.status='cancelled';persist();message('resultTitle','Foglalás lemondva');message('bookingStatus',demo?'Az időpont felszabadult. Nincs e-mail.':'Az időpont felszabadult. Az értesítést külön dolgozzuk fel.');}catch(error){message('bookingStatus',safeError(error));$('cancelBooking').disabled=false;}finally{busy=false;}});
$('newBooking').addEventListener('click',()=>{if(busy)return;saved=null;pending=null;if(!demo)store.remove(guestKey());$('bookingResult').hidden=true;formLock(false);$('bookButton').textContent=demo?'Próbafoglalás rögzítése':'Időpont rögzítése';$('privacyAccepted').checked=false;message('bookingStatus','');loadSlots();});
$('ownerDate').addEventListener('change',loadDay);$('refreshDay').addEventListener('click',loadDay);
for(const [id,delta] of [['previousDay',-1],['nextDay',1]])$(id).addEventListener('click',()=>{if(busy)return;$('ownerDate').value=addDays($('ownerDate').value||dayKey(),delta);loadDay();});
$('ownerLogin').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;busy=true;const form=event.currentTarget;try{await api.login(form.elements.email.value,form.elements.password.value);form.reset();message('loginStatus','');await showOwner();}catch{message('loginStatus','A belépés nem sikerült. Ellenőrizd az adatokat.');}finally{busy=false;}});
$('ownerLogout').addEventListener('click',async()=>{if(busy)return;try{await api.logout();ownerRequests.clear();await showOwner();}catch{message('ownerStatus','A kijelentkezés nem sikerült.');}});
$('dayBookings').addEventListener('click',async event=>{const el=event.target.closest('button');if(!el||busy)return;if(el.hasAttribute('data-resume-owner'))return ownerAction(null,'resume',{});const row=ownerRows.find(r=>r.bookingId===(el.dataset.booking||el.dataset.move));if(!row)return;if(el.dataset.status)return ownerAction(row,'ownerStatus',{status:el.dataset.status});
  if(el.dataset.move){moveTarget=row;$('moveForm')?.remove();const form=document.createElement('form');form.id='moveForm';form.className='card move-form';form.innerHTML=`<h3>Áthelyezés · ${e(row.name)}</h3><p class="muted">A szolgáltatás ára és időtartama nem változik. Az új időpontot a mentéskor újra ellenőrizzük.</p><label>Új nap<input name="date" type="date" required min="${dayKey()}" max="${addDays(dayKey(),settings.horizonDays)}" value="${e(row.date)}"></label><button type="button" data-load-move>Szabad időpontok lekérése</button><label>Új kezdés<select name="start" required disabled><option value="">Először kérd le az időpontokat.</option></select></label><button type="submit" disabled>Áthelyezés mentése</button><p class="status" role="status"></p>`;$('dayBookings').append(form);
    let moveEpoch=0;const invalidate=()=>{moveEpoch++;form.elements.start.disabled=true;form.querySelector('[type="submit"]').disabled=true;};form.elements.date.addEventListener('change',invalidate);
    form.querySelector('[data-load-move]').addEventListener('click',async()=>{const date=form.elements.date.value;invalidate();const expected=moveEpoch;try{const result=await api.ownerMoveSlots({tenantId,bookingId:row.bookingId,date});if(expected!==moveEpoch||moveTarget!==row)return;form.elements.start.innerHTML=result.slots.map(s=>`<option value="${e(s.start)}">${e(time(s.start))}</option>`).join('')||'<option value="">Nincs szabad időpont.</option>';form.elements.start.disabled=!result.slots.length;form.querySelector('[type="submit"]').disabled=!result.slots.length;}catch(error){if(expected===moveEpoch)form.querySelector('.status').textContent=safeError(error);}});
    form.addEventListener('submit',event=>{event.preventDefault();if(moveTarget!==row)return;ownerAction(row,'ownerMove',{date:form.elements.date.value,start:form.elements.start.value});});form.scrollIntoView({block:'center',behavior:'smooth'});
  }
});
$('confirmLinkCancel').addEventListener('click',async()=>{if(!api||!cancelRequest||busy)return;busy=true;$('confirmLinkCancel').disabled=true;try{await api.cancelBooking(cancelRequest);store.remove(cancelStateKey);message('cancelStatus','A foglalást lemondtuk.');}catch(error){message('cancelStatus',safeError(error));$('confirmLinkCancel').disabled=false;}finally{busy=false;}});
$('downloadCancellation').addEventListener('click',()=>{if(!saved||!pending)return;const url=location.origin+location.pathname+'#tenant='+encodeURIComponent(tenantId)+'&booking='+encodeURIComponent(saved.bookingId)+'&token='+pending.cancellationToken;const blob=new Blob([saved.service.name+'\n'+saved.start+'\nLemondási link (őrizd biztonságban):\n'+url],{type:'text/plain;charset=utf-8'});const link=URL.createObjectURL(blob),a=document.createElement('a');a.href=link;a.download='foglalas-lemondasi-link.txt';a.click();setTimeout(()=>URL.revokeObjectURL(link),1000);});
window.addEventListener('beforeunload',event=>{if(pending&&!saved){event.preventDefault();event.returnValue='';}});
async function start(){try{api=demo?createDemoApi():await liveBookingApi();$('modeNotice').textContent=demo?'BEMUTATÓ • Nem valódi szolgáltató. Csak próbaadatok, a lap bezárásáig. Nincs e-mail, fizetés vagy valódi foglalás.':'OVEXI időpontfoglalás • Az időpontok magyarországi idő szerint jelennek meg.';
    if(cancelRequest&&!demo){$('guestPanel').hidden=true;$('ownerPanel').hidden=true;$('cancelPanel').hidden=false;$('guestTab').disabled=true;$('ownerTab').disabled=true;return;}
    if(demo)tenantId='demo';else if(!/^[a-zA-Z0-9_-]{1,80}$/.test(tenantId))throw Error('Hiányzik a szolgáltató azonosítója. Kérd el a szolgáltató saját foglalási linkjét.');settings=await api.publicConfig({tenantId});message('businessName',settings.businessName);$('privacyLink').href=settings.privacyUrl;$('serviceSelect').innerHTML=settings.services.map(s=>`<option value="${e(s.id)}">${e(s.name)} · ${s.durationMinutes} perc · ${money(s.priceHuf)}</option>`).join('');$('bookingDate').min=dayKey();$('bookingDate').max=addDays(dayKey(),settings.horizonDays);$('bookingDate').value=api.defaultDate||dayKey();$('ownerDate').value=$('bookingDate').value;formLock(false);if(demo){$('guestName').value='Próba Vendég';$('guestEmail').value='proba@example.invalid';$('guestName').readOnly=true;$('guestEmail').readOnly=true;$('bookButton').textContent='Próbafoglalás rögzítése';}restore();if(saved)displaySaved();else if(pending){formLock(true);$('bookButton').disabled=false;$('bookButton').textContent='Korábbi foglalás újraellenőrzése';message('bookingStatus','Félbemaradt foglalás. A gomb az eredeti kérést ellenőrzi újra.');}else await loadSlots();}
  catch(error){formLock(true);$('guestTab').disabled=true;$('ownerTab').disabled=true;$('modeNotice').textContent='Az éles foglalás még nem elérhető.';message('globalStatus',safeError(error));}}
start();
