import {confirmAction} from './confirm-action.js?v=20260902-3';
import {recordEditor} from './record-editor.js?v=20260902-3';
import {downloadPackage} from "./artifact-download.js?v=20260902-2";
import {escapeHtml as e,safeStorage,reliableAction,safeLink} from './customer-model.js?v=20260902-1';
export function installProduction({getData,identity,call,refresh,notify}){
  const host=document.getElementById('productionList'),form=document.createElement('form');form.className='surface';
  form.innerHTML='<h3>Egyedi weboldal és marketinganyag</h3><p>Minden munka saját oldalszerkezetet, megjelenést és kreatívokat kap a brief alapján. Az eredmény ellenőrizhető és szerkeszthető; a tervezés több percig is tarthat.</p><label>Rendelés<select name="orderId" required></select></label><label>Főcím<input name="headline" maxlength="160"></label><label>Cégbemutatás<textarea name="description" maxlength="4000" rows="4"></textarea></label><label>Nyilvános kapcsolatfelvételi URL<input name="contactUrl" type="url" placeholder="https://..."></label><button type="button" data-ai>Szövegek készítése AI-val a csomag alapján</button><label>Tervezési irány<textarea name="direction" rows="3" maxlength="4000" placeholder="Milyen hangulat, megjelenés és üzleti cél illik ehhez a vállalkozáshoz?"></textarea></label><details><summary>Szolgáltatások és marketingtartalom szerkesztése</summary><h4>Szolgáltatások</h4><div data-services></div><h4>Posztok</h4><div data-posts></div><h4>Blogcikkek</h4><div data-blogs></div><h4>Hírlevelek</h4><div data-emails></div></details><button type="submit">Egyedi tervezés indítása</button><p role="status"></p>';
  host.before(form);const store=safeStorage(()=>sessionStorage);let actions=new Map(),busy=false,generation=0; const copyLog=document.createElement('section');host.after(copyLog);
  function lock(value){for(const field of form.elements)field.disabled=value;}
  function action(key){if(!actions.has(key))actions.set(key,reliableAction(store,`ovexi-production:${identity()}:${key}`));return actions.get(key);}
  const articles=[{key:'title',label:'Cím',required:true,maxLength:160},{key:'body',label:'Szöveg',type:'textarea',required:true,maxLength:12000}];
  const editors={services:recordEditor(form.querySelector('[data-services]'),{label:'Szolgáltatás',max:12,fields:[{key:'title',label:'Szolgáltatás neve',required:true,maxLength:120},{key:'description',label:'Leírás',type:'textarea',required:true,maxLength:1000}]}),posts:recordEditor(form.querySelector('[data-posts]'),{label:'Poszt',max:80,fields:[{key:'day',label:'Javasolt nap (1–31)',type:'number',min:1,max:31,default:1,required:true},{key:'channel',label:'Csatorna',default:'Facebook',maxLength:50},...articles.map(f=>f.key==='body'?{...f,maxLength:4000}:f)]}),blogs:recordEditor(form.querySelector('[data-blogs]'),{label:'Blogcikk',max:8,fields:articles}),emailDrafts:recordEditor(form.querySelector('[data-emails]'),{label:'Hírlevél',max:8,fields:articles})};
  function contentValue(){const value=Object.fromEntries(Object.entries(editors).map(([key,editor])=>[key,editor.get()]));for(const key of ['headline','description','contactUrl'])if(form.elements[key].value.trim())value[key]=form.elements[key].value.trim();return value;}
  function setContent(content={}){for(const [key,editor] of Object.entries(editors))editor.set(content[key]||[]);for(const key of ['headline','description','contactUrl'])form.elements[key].value=content[key]||'';}
  function loadContent(row){form.elements.orderId.value=row.orderId;setContent(row.content);form.scrollIntoView({block:'center'});}
  form.elements.orderId.addEventListener('change',()=>{setContent();form.elements.direction.value='';form.querySelector('[role=status]').textContent='';});
  copyLog.addEventListener('click',event=>{const button=event.target.closest('[data-copy]');if(!button||busy)return;const row=(getData().production_copy_jobs||[]).find(r=>r.id===button.dataset.copy);if(row?.content)loadContent(row);});
  function render(){
    const data=getData(),selected=form.elements.orderId.value;
    form.elements.orderId.innerHTML='<option value="">Válassz rendelést</option>'+data.orders.filter(r=>!['completed','cancelled'].includes(r.status)).map(r=>`<option value="${e(r.id)}">${e(r.orderNumber)} · ${e(r.companyName)}</option>`).join('');form.elements.orderId.value=selected;
    copyLog.innerHTML='<h3>AI-szövegkészítés naplója</h3>'+((data.production_copy_jobs||[]).map(r=>`<article class="record-card"><strong>${e(data.orders.find(o=>o.id===r.orderId)?.orderNumber||r.orderId)}</strong><p>${e(({ready:'Elkészült',generating:'Folyamatban',needs_review:'Bizonytalan eredmény, ellenőrzés szükséges',failed:'Nem készült teljes anyag'})[r.status]||r.status)}</p>${r.content?`<button type="button" data-copy="${e(r.id)}">Elkészült szöveg betöltése</button>`:''}<p>${e((r.missingInformation||[]).join('; ')||r.errorCode||'')}</p></article>`).join('')||'<p>Még nincs AI-szövegkészítés.</p>');
    host.innerHTML=data.production_jobs.map(r=>`<article class="record-card"><h3>${e(r.companyName||r.orderNumber||'Gyártási munka')}</h3><p>${e(r.files?(r.manifest?.generator==='ovexi-bespoke-v1'?'Egyedi tervezet elkészült':'Korábbi mentett változat'):({generating:'Egyedi tervezés folyamatban',needs_review:'A tervezés eredménye ellenőrzendő',generation_failed:'A tervezés nem zárult kész anyaggal'})[r.status]||'Korábbi gyártási terv')} · brief ${e(r.briefRevision??0)}</p>${safeLink(r.previewUrl)&&!r.revokedAt?`<p><a href="${e(r.previewUrl)}" target="_blank" rel="noreferrer">Weboldal megnyitása ↗</a> · <a href="${e(r.marketingUrl)}" target="_blank" rel="noreferrer">Marketinganyag ↗</a></p><button type="button" data-share="${e(r.id)}">Weboldal küldése ügyfél-jóváhagyásra</button> <button type="button" data-marketing="${e(r.id)}">Marketinganyag küldése jóváhagyásra</button> <button type="button" data-revoke="${e(r.id)}">Előnézeti hozzáférés visszavonása</button>`:''}${r.files?`<p><button type="button" data-archive="${e(r.id)}">Teljes csomag letöltése (ZIP, PNG-képekkel)</button> <button type="button" data-edit="${e(r.id)}">Tartalom betöltése szerkesztéshez</button></p><details><summary>Fájlok letöltése egyenként</summary><div class="record-actions">${Object.keys(r.files).map(name=>`<button class="secondary" type="button" data-download="${e(r.id)}" data-file="${e(name)}">${e(name)} letöltése</button>`).join('')}</div></details>`:''}${r.manifest?.concept?`<h4>Tervezési koncepció</h4><p>${e(r.manifest.concept)}</p><ul>${(r.manifest.decisions||[]).map(t=>`<li>${e(t)}</li>`).join('')}</ul>`:''}<details><summary>Hátralévő egyeztetések és ellenőrzések</summary><ul>${(r.manifest?.missing||['A korábbi terv részleteit az anyagban találod.']).map(t=>`<li>${e(t)}</li>`).join('')}</ul></details></article>`).join('')||'<p>Még nincs elkészített anyag.</p>';
  }
  form.querySelector('[data-ai]').addEventListener('click',async()=>{if(busy)return;const row=getData().orders.find(r=>r.id===form.elements.orderId.value);if(!row)return notify('Válassz rendelést.');busy=true;const ticket=generation;lock(true);form.querySelector('[data-ai]').disabled=true;form.querySelector('[role=status]').textContent='AI-szövegek készülnek a meglévő havi költségkereten belül…';try{const source=contentValue();const result=await action('copy:'+row.id).send({orderId:row.id,briefRevision:Number(row.briefRevision||0),source},payload=>call('generateProductionCopy',payload));if(ticket!==generation)return;setContent(result.content);form.querySelector('[role=status]').textContent='A szövegek elkészültek. Ellenőrizd, majd készítsd el az anyagokat. Hiányzó adatok: '+(result.missingInformation.join('; ')||'nincs jelzett hiány');await refresh();}catch(error){if(ticket!==generation)return;form.querySelector('[role=status]').textContent=error.message||'Az AI-kérés eredménye bizonytalan.';}finally{if(ticket===generation){busy=false;lock(false);form.querySelector('[data-ai]').disabled=false;}}});
  form.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const row=getData().orders.find(r=>r.id===form.elements.orderId.value);if(!row)return;busy=true;const ticket=generation;lock(true);form.querySelector('[type=submit]').disabled=true;
    try{form.querySelector('[role=status]').textContent='Egyedi oldalszerkezet, megjelenés és kreatívok készülnek. A folyamat több percig is tarthat; az eredmény a naplóban megmarad.';const content=contentValue();const result=await action('generate:'+row.id).send({orderId:row.id,briefRevision:Number(row.briefRevision||0),content,direction:form.elements.direction.value.trim()},payload=>call('generateProductionArtifacts',payload));if(ticket!==generation)return;form.querySelector('[role=status]').textContent='Az anyagok elkészültek. Ellenőrizd őket az alábbi listában.';await refresh();}
    catch(error){if(ticket!==generation)return;form.querySelector('[role=status]').textContent=error.message||'A művelet nem sikerült; próbáld újra.';}finally{if(ticket===generation){busy=false;lock(false);form.querySelector('[type=submit]').disabled=false;}}
  });
  host.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;const id=b.dataset.archive||b.dataset.download||b.dataset.share||b.dataset.marketing||b.dataset.edit||b.dataset.revoke,row=getData().production_jobs.find(r=>r.id===id);if(!row)return;
    if(b.dataset.archive){b.disabled=true;try{await downloadPackage(row.files,'ovexi-'+row.id.slice(0,12)+'.zip');}catch(error){notify(error.message);}finally{b.disabled=false;}return;}
    if(b.dataset.download){const value=row.files?.[b.dataset.file];if(typeof value!=='string')return;const blob=new Blob([value],{type:'application/octet-stream'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=b.dataset.file;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
    if(b.dataset.edit){if(!busy)loadContent(row);return;}
    if(busy)return;busy=true;const ticket=generation;b.disabled=true;
    try{if(b.dataset.revoke){if(!await confirmAction('Visszavonod ennek a változatnak a megnyitási linkjét?'))return;await call('revokeProductionPreview',{jobId:row.id});}
      else{const flow=getData().order_workflows.find(f=>f.orderId===row.orderId||f.id===row.orderId),order=getData().orders.find(o=>o.id===row.orderId);if(!flow||!order)throw Error('Frissítsd a rendeléseket.');if(Number(order.briefRevision||0)!==row.briefRevision)throw Error('A brief megváltozott. Készíts új anyagot.');await action('share:'+row.id+':'+(b.dataset.marketing?'marketing':'website')).send({orderId:row.orderId,revision:Number(flow.revision||0),title:b.dataset.marketing?'Marketinganyag':'Weboldal előnézete',url:b.dataset.marketing?row.marketingUrl:row.previewUrl,note:'Kérjük, ellenőrizd a tartalmat és jelezd a szükséges módosításokat.'},payload=>call('saveOrderPreview',payload));}
      if(ticket!==generation)return;await refresh();notify('Mentve.');
    }catch(error){if(ticket===generation)notify(error.message||'A művelet nem sikerült.');}finally{if(ticket===generation){busy=false;b.disabled=false;}}
  });
  return {render,reset(){generation++;busy=false;actions.clear();form.reset();setContent();lock(false);form.querySelectorAll('button').forEach(b=>b.disabled=false);form.querySelector('[role=status]').textContent='';host.innerHTML='';copyLog.innerHTML='';}};
}
