import {downloadPackage} from "./artifact-download.js?v=20260902-2";
import {escapeHtml as e,safeStorage,reliableAction,safeLink} from './customer-model.js?v=20260902-1';
export function installProduction({getData,identity,call,refresh,notify}){
  const host=document.getElementById('productionList'),form=document.createElement('form');form.className='surface';
  form.innerHTML='<h3>Weboldal és marketinganyag készítése</h3><p>A briefből megnyitható HTML-oldal, marketingelőnézet és letölthető tartalomnaptár készül. A tartalom szerkeszthető, minden változat külön megmarad.</p><label>Rendelés<select name="orderId" required></select></label><label>Főcím<input name="headline" maxlength="160"></label><label>Cégbemutatás<textarea name="description" maxlength="4000" rows="4"></textarea></label><label>Nyilvános kapcsolatfelvételi URL<input name="contactUrl" type="url" placeholder="https://..."></label><button type="button" data-ai>Szövegek készítése AI-val a csomag alapján</button><details><summary>Részletes tartalom szerkesztése</summary><label>Tartalom felülírása (JSON, opcionális)<textarea name="content" rows="7" placeholder=\'{"headline":"Főcím","contactUrl":"https://...","services":[{"title":"Szolgáltatás","description":"Leírás"}]}\'></textarea></label></details><button type="submit">Ellenőrizhető anyagok elkészítése</button><p role="status"></p>';
  host.before(form);const store=safeStorage(()=>sessionStorage);let actions=new Map(),busy=false,generation=0; const copyLog=document.createElement('section');host.after(copyLog);
  function action(key){if(!actions.has(key))actions.set(key,reliableAction(store,`ovexi-production:${identity()}:${key}`));return actions.get(key);}
  function loadContent(row){form.elements.orderId.value=row.orderId;form.elements.content.value=JSON.stringify(row.content,null,2);for(const key of ['headline','description','contactUrl'])form.elements[key].value=row.content[key]||'';form.scrollIntoView({block:'center'});}
  copyLog.addEventListener('click',event=>{const button=event.target.closest('[data-copy]');if(!button||busy)return;const row=(getData().production_copy_jobs||[]).find(r=>r.id===button.dataset.copy);if(row?.content)loadContent(row);});
  function render(){
    const data=getData(),selected=form.elements.orderId.value;
    form.elements.orderId.innerHTML='<option value="">Válassz rendelést</option>'+data.orders.filter(r=>!['completed','cancelled'].includes(r.status)).map(r=>`<option value="${e(r.id)}">${e(r.orderNumber)} · ${e(r.companyName)}</option>`).join('');form.elements.orderId.value=selected;
    copyLog.innerHTML='<h3>AI-szövegkészítés naplója</h3>'+((data.production_copy_jobs||[]).map(r=>`<article class="record-card"><strong>${e(data.orders.find(o=>o.id===r.orderId)?.orderNumber||r.orderId)}</strong><p>${e(({ready:'Elkészült',generating:'Folyamatban',needs_review:'Bizonytalan eredmény, ellenőrzés szükséges',failed:'Nem készült teljes anyag'})[r.status]||r.status)}</p>${r.content?`<button type="button" data-copy="${e(r.id)}">Elkészült szöveg betöltése</button>`:''}<p>${e((r.missingInformation||[]).join('; ')||r.errorCode||'')}</p></article>`).join('')||'<p>Még nincs AI-szövegkészítés.</p>');
    host.innerHTML=data.production_jobs.map(r=>`<article class="record-card"><h3>${e(r.companyName||r.orderNumber||'Gyártási munka')}</h3><p>${r.files?'Elkészült, ellenőrizhető anyagok':'Korábbi gyártási terv'} · brief ${e(r.briefRevision??0)}</p>${safeLink(r.previewUrl)&&!r.revokedAt?`<p><a href="${e(r.previewUrl)}" target="_blank" rel="noreferrer">Weboldal megnyitása ↗</a> · <a href="${e(r.marketingUrl)}" target="_blank" rel="noreferrer">Marketinganyag ↗</a></p><button type="button" data-share="${e(r.id)}">Weboldal küldése ügyfél-jóváhagyásra</button> <button type="button" data-marketing="${e(r.id)}">Marketinganyag küldése jóváhagyásra</button> <button type="button" data-revoke="${e(r.id)}">Előnézeti hozzáférés visszavonása</button>`:''}${r.files?`<p><button type="button" data-archive="${e(r.id)}">Teljes csomag letöltése (ZIP, PNG-képekkel)</button> <button type="button" data-edit="${e(r.id)}">Tartalom betöltése szerkesztéshez</button></p><div class="record-actions">${Object.keys(r.files).map(name=>`<button class="secondary" type="button" data-download="${e(r.id)}" data-file="${e(name)}">${e(name)} letöltése</button>`).join('')}</div>`:''}<details><summary>Hátralévő egyeztetések és ellenőrzések</summary><pre>${e(JSON.stringify(r.manifest?.missing||r.plan||{},null,2))}</pre></details></article>`).join('')||'<p>Még nincs elkészített anyag.</p>';
  }
  form.querySelector('[data-ai]').addEventListener('click',async()=>{if(busy)return;const row=getData().orders.find(r=>r.id===form.elements.orderId.value);if(!row)return notify('Válassz rendelést.');busy=true;const ticket=generation;form.elements.orderId.disabled=true;form.querySelector('[data-ai]').disabled=true;form.querySelector('[role=status]').textContent='AI-szövegek készülnek a meglévő havi költségkereten belül…';try{const source=form.elements.content.value.trim()?JSON.parse(form.elements.content.value):{};for(const key of ['headline','description','contactUrl'])if(form.elements[key].value.trim())source[key]=form.elements[key].value.trim();const result=await action('copy:'+row.id).send({orderId:row.id,briefRevision:Number(row.briefRevision||0),source},payload=>call('generateProductionCopy',payload));if(ticket!==generation)return;form.elements.content.value=JSON.stringify(result.content,null,2);for(const key of ['headline','description','contactUrl'])form.elements[key].value=result.content[key]||'';form.querySelector('[role=status]').textContent='A szövegek elkészültek. Ellenőrizd, majd készítsd el az anyagokat. Hiányzó adatok: '+(result.missingInformation.join('; ')||'nincs jelzett hiány');await refresh();}catch(error){if(ticket!==generation)return;form.querySelector('[role=status]').textContent=error.message||'Az AI-kérés eredménye bizonytalan.';}finally{if(ticket===generation){busy=false;form.elements.orderId.disabled=false;form.querySelector('[data-ai]').disabled=false;}}});
  form.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const row=getData().orders.find(r=>r.id===form.elements.orderId.value);if(!row)return;busy=true;const ticket=generation;form.elements.orderId.disabled=true;form.querySelector('[type=submit]').disabled=true;
    try{const content=form.elements.content.value.trim()?JSON.parse(form.elements.content.value):{};for(const key of ['headline','description','contactUrl'])if(form.elements[key].value.trim())content[key]=form.elements[key].value.trim();const result=await action('generate:'+row.id).send({orderId:row.id,briefRevision:Number(row.briefRevision||0),content},payload=>call('generateProductionArtifacts',payload));if(ticket!==generation)return;form.querySelector('[role=status]').textContent='Az anyagok elkészültek. Ellenőrizd őket az alábbi listában.';await refresh();}
    catch(error){if(ticket!==generation)return;form.querySelector('[role=status]').textContent=error.message||'A művelet nem sikerült; próbáld újra.';}finally{if(ticket===generation){busy=false;form.elements.orderId.disabled=false;form.querySelector('[type=submit]').disabled=false;}}
  });
  host.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;const id=b.dataset.archive||b.dataset.download||b.dataset.share||b.dataset.marketing||b.dataset.edit||b.dataset.revoke,row=getData().production_jobs.find(r=>r.id===id);if(!row)return;
    if(b.dataset.archive){b.disabled=true;try{await downloadPackage(row.files,'ovexi-'+row.id.slice(0,12)+'.zip');}catch(error){notify(error.message);}finally{b.disabled=false;}return;}
    if(b.dataset.download){const value=row.files?.[b.dataset.file];if(typeof value!=='string')return;const blob=new Blob([value],{type:'application/octet-stream'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=b.dataset.file;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
    if(b.dataset.edit){if(!busy)loadContent(row);return;}
    if(busy)return;busy=true;const ticket=generation;b.disabled=true;
    try{if(b.dataset.revoke){if(!confirm('Visszavonod ennek a változatnak a megnyitási linkjét?'))return;await call('revokeProductionPreview',{jobId:row.id});}
      else{const flow=getData().order_workflows.find(f=>f.orderId===row.orderId||f.id===row.orderId),order=getData().orders.find(o=>o.id===row.orderId);if(!flow||!order)throw Error('Frissítsd a rendeléseket.');if(Number(order.briefRevision||0)!==row.briefRevision)throw Error('A brief megváltozott. Készíts új anyagot.');await action('share:'+row.id+':'+(b.dataset.marketing?'marketing':'website')).send({orderId:row.orderId,revision:Number(flow.revision||0),title:b.dataset.marketing?'Marketinganyag':'Weboldal előnézete',url:b.dataset.marketing?row.marketingUrl:row.previewUrl,note:'Kérjük, ellenőrizd a tartalmat és jelezd a szükséges módosításokat.'},payload=>call('saveOrderPreview',payload));}
      if(ticket!==generation)return;await refresh();notify('Mentve.');
    }catch(error){if(ticket===generation)notify(error.message||'A művelet nem sikerült.');}finally{if(ticket===generation){busy=false;b.disabled=false;}}
  });
  return {render,reset(){generation++;busy=false;actions.clear();form.reset();form.elements.orderId.disabled=false;form.querySelectorAll('button').forEach(b=>b.disabled=false);form.querySelector('[role=status]').textContent='';host.innerHTML='';copyLog.innerHTML='';}};
}
