const test=require('node:test'),assert=require('node:assert/strict');
const domain=require('../proposal-domain');
const valid=()=>({requestId:'e4a1bcdb-7b27-4655-a50a-1f59aaa0ff21',contactName:'Teszt Elek',companyName:'Minta Szerviz',email:'TESZT@example.hu',phone:'+36 30 123 4567',businessType:'autószerviz',currentUrl:'facebook.com/mintaszerviz',mainChallenge:'Telefonon és papíron kezeljük az ajánlatkéréseket.',needs:['quotes','administration'],contactConsent:true,privacyAccepted:true});
test('proposal: normalizes and accepts a complete opt-in request',()=>{const result=domain.validateProposal(valid());assert.equal(result.email,'teszt@example.hu');assert.equal(result.currentUrl,'https://facebook.com/mintaszerviz');assert.deepEqual(result.needs,['quotes','administration']);assert.equal(result.source,'website_proposal_form');});
test('proposal: keeps social landing attribution without weakening validation',()=>{const result=domain.validateProposal({...valid(),landingVariant:'social',campaignSource:'tiktok',campaignName:'weboldal_indulas',campaignContent:'hook_01'});assert.equal(result.source,'social_landing');assert.equal(result.campaignSource,'tiktok');assert.equal(result.campaignName,'weboldal_indulas');assert.equal(result.campaignContent,'hook_01');});
test('proposal: rejects a missing reply channel, either missing consent flag or an unsafe url',()=>{for(const patch of [{email:'bad'},{email:''},{contactConsent:false},{privacyAccepted:false},{requestId:'nope'},{currentUrl:'javascript:alert(1)'}])assert.throws(()=>domain.validateProposal({...valid(),...patch}));});
test('proposal: accepts a request that fills in nothing but the email and the tick',()=>{const result=domain.validateProposal({requestId:'e4a1bcdb-7b27-4655-a50a-1f59aaa0ff21',email:'teszt@example.hu',contactConsent:true,privacyAccepted:true});assert.equal(result.email,'teszt@example.hu');assert.equal(result.contactName,'');assert.equal(result.businessType,'');assert.equal(result.mainChallenge,'');assert.deepEqual(result.needs,[]);});
test('proposal: still drops forged need values instead of storing them',()=>{assert.deepEqual(domain.validateProposal({...valid(),needs:['quotes','forged']}).needs,['quotes']);});
test('proposal: fingerprint is stable and input-sensitive',()=>{assert.equal(domain.fingerprint(valid()),domain.fingerprint(valid()));assert.notEqual(domain.fingerprint(valid()),domain.fingerprint({...valid(),email:'mas@example.hu'}));});
