"use strict";
// Source backup is Git's responsibility. This captures Firestore document values,
// including subcollections, encrypted under the current Windows user's DPAPI key.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),zlib=require('node:zlib'),{spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),directory=path.join(root,'ops/backups'),keyFile=path.join(root,'ops/backup-key.dpapi');
function dpapi(input,protect){const method=protect?'Protect':'Unprotect';const script=`Add-Type -AssemblyName System.Security; $bytes=[Convert]::FromBase64String([Console]::In.ReadToEnd().Trim()); [Convert]::ToBase64String([Security.Cryptography.ProtectedData]::${method}($bytes,$null,[Security.Cryptography.DataProtectionScope]::CurrentUser))`;
  const r=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{input:input.toString('base64'),encoding:'utf8',windowsHide:true});if(r.status!==0)throw Error('Windows kulcsvédelem sikertelen.');return Buffer.from(r.stdout.trim(),'base64');}
function key(create=false){if(!fs.existsSync(keyFile)){if(!create)throw Error('A mentési kulcs hiányzik.');fs.mkdirSync(path.dirname(keyFile),{recursive:true});fs.writeFileSync(keyFile,dpapi(crypto.randomBytes(32),true),{flag:'wx'});}return dpapi(fs.readFileSync(keyFile),false);}
function encrypt(value,k){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',k,iv),data=Buffer.concat([cipher.update(zlib.gzipSync(Buffer.from(JSON.stringify(value)))),cipher.final()]);return JSON.stringify({format:'ovexi-backup-v1',iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),data:data.toString('base64')});}
function decrypt(value,k){const b=JSON.parse(value);if(b.format!=='ovexi-backup-v1')throw Error('Ismeretlen mentésformátum.');const decipher=crypto.createDecipheriv('aes-256-gcm',k,Buffer.from(b.iv,'base64'));decipher.setAuthTag(Buffer.from(b.tag,'base64'));return JSON.parse(zlib.gunzipSync(Buffer.concat([decipher.update(Buffer.from(b.data,'base64')),decipher.final()])));}
async function exportDb(client){const base='projects/ovexi-6ef38/databases/(default)/documents',documents=[],collections=new Set();
  async function walk(parent){let pageToken;do{const list=(await client.post(parent+':listCollectionIds',{pageSize:100,...(pageToken?{pageToken}:{})})).body;for(const collection of list.collectionIds||[]){collections.add(collection);let token;do{const result=(await client.get(parent+'/'+encodeURIComponent(collection),{queryParams:{pageSize:100,showMissing:true,...(token?{pageToken:token}:{})}})).body;for(const doc of result.documents||[]){if(doc.fields)documents.push({path:doc.name.slice(base.length+1),fields:doc.fields});await walk(doc.name);}token=result.nextPageToken;}while(token);}pageToken=list.nextPageToken;}while(pageToken);}
  await walk(base);return {schemaVersion:1,project:'ovexi-6ef38',exportedAt:new Date().toISOString(),consistency:'paginated-live-read-not-a-point-in-time-snapshot',documents,collections:[...collections].sort()};
}
async function restoreEmulator(backup){const host=process.env.FIRESTORE_EMULATOR_HOST;if(!/^127\.0\.0\.1:\d+$/.test(host||''))throw Error('Kizárólag helyi emulátorba állítható vissza.');const project='demo-ovexi-restore',base=`http://${host}/v1/projects/${project}/databases/(default)/documents`;let checked=0;
  for(const doc of backup.documents){if(!/^[^?#]+$/.test(doc.path)||doc.path.split('/').some(s=>['.','..',''].includes(s)))throw Error('Hibás dokumentumútvonal.');const url=base+'/'+doc.path.split('/').map(encodeURIComponent).join('/');const r=await fetch(url,{method:'PATCH',headers:{'content-type':'application/json','Authorization':'Bearer owner'},body:JSON.stringify({fields:doc.fields})});if(!r.ok)throw Error('Visszaállítás sikertelen: HTTP '+r.status);const read=await fetch(url,{headers:{Authorization:'Bearer owner'}});if(!read.ok)throw Error('Visszaolvasás sikertelen.');const result=await read.json();if(canonical(result.fields||{})!==canonical(doc.fields))throw Error('A visszaállított adat eltér.');checked++;}
  return {restoredAndVerified:checked,project};
}
function canonical(x){if(x&&typeof x==='object'&&Object.keys(x).length===1&&typeof x.timestampValue==='string')return JSON.stringify({timestampValue:new Date(x.timestampValue).toISOString()});if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';if(x&&typeof x==='object')return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';return JSON.stringify(x);}
async function main(){const command=process.argv[2];if(command==='create'){const {client}=await require('./firebase-client.cjs').client();const snapshot=await exportDb(client),encoded=encrypt(snapshot,key(true));fs.mkdirSync(directory,{recursive:true});const file=path.join(directory,new Date().toISOString().replace(/[:.]/g,'-')+'.ovxb');fs.writeFileSync(file,encoded,{flag:'wx'});const checked=decrypt(fs.readFileSync(file,'utf8'),key());if(canonical(snapshot)!==canonical(checked))throw Error('Mentés ellenőrzése sikertelen.');console.log(JSON.stringify({file,documents:snapshot.documents.length,collections:snapshot.collections.length,encrypted:true,roundTripVerified:true}));}
  else if(command==='verify'||command==='restore-emulator'){const file=path.resolve(process.argv[3]||'');if(!file.startsWith(directory+path.sep)||path.extname(file)!=='.ovxb')throw Error('A mentési könyvtár fájlja szükséges.');const snapshot=decrypt(fs.readFileSync(file,'utf8'),key());console.log(JSON.stringify(command==='verify'?{documents:snapshot.documents.length,verified:true}:await restoreEmulator(snapshot)));}else throw Error('Használat: node tools/backup.cjs create | verify <fájl> | restore-emulator <fájl>');}
if(require.main===module)main().catch(error=>{console.error(error.message);process.exitCode=1;});
module.exports={encrypt,decrypt,canonical,restoreEmulator};
