"use strict";
const fs=require('node:fs'),path=require('node:path'),dns=require('node:dns').promises;
const root=path.resolve(__dirname,'..');
async function main(){process.loadEnvFile(path.join(root,'functions/.env.ovexi-6ef38'));const {secret,client}=await require('./firebase-client.cjs').client();const checks={checkedAt:new Date().toISOString(),paymentsEnabled:process.env.PAYMENTS_ENABLED==='true',billingoEnabled:process.env.BILLINGO_ENABLED==='true',bookingEnabled:process.env.BOOKING_ENABLED==='true',aiProductionEnabled:process.env.AI_PRODUCTION_ENABLED==='true'};
  try{const Stripe=require('../functions/node_modules/stripe'),key=await secret('STRIPE_SECRET_KEY'),stripe=new Stripe(key,{maxNetworkRetries:0,timeout:15000}),account=await stripe.accounts.retrieve();checks.stripe={keyMode:key.startsWith('sk_test_')?'test':'live',chargesEnabled:account.charges_enabled,payoutsEnabled:account.payouts_enabled,detailsSubmitted:account.details_submitted,requirements:account.requirements?.currently_due||[]};const endpoints=await stripe.webhookEndpoints.list({limit:100});const needed=require('../functions/commerce-domain').SUPPORTED_EVENTS;checks.stripe.webhooks=endpoints.data.filter(e=>e.url.includes('ovexi-6ef38')).map(e=>({enabled:e.status==='enabled',mode:e.livemode?'live':'test',missingEvents:e.enabled_events.includes('*')?[]:needed.filter(x=>!e.enabled_events.includes(x))}));}catch{checks.stripe={status:'unavailable'};}
  try{const key=await secret('BILLINGO_API_KEY'),response=await fetch('https://api.billingo.hu/v3/document-blocks',{headers:{'X-API-KEY':key},signal:AbortSignal.timeout(15000)});checks.billingo={secretConfigured:true,readOnlyStatus:response.status,blockConfigured:Number(process.env.BILLINGO_BLOCK_ID)>0};}catch{checks.billingo={secretConfigured:false,status:'not_verified'};}
  checks.dns={};for(const [key,name] of [['spf','ovexi.hu'],['dmarc','_dmarc.ovexi.hu'],['dkimDefault','default._domainkey.ovexi.hu']]){try{const records=(await dns.resolveTxt(name)).map(r=>r.join(''));checks.dns[key]={found:records.some(s=>key==='spf'?s.startsWith('v=spf1'):key==='dmarc'?s.startsWith('v=DMARC1'):s.includes('p='))};}catch{checks.dns[key]={found:false};}}
  const base='projects/ovexi-6ef38/databases/(default)';try{checks.firestoreBackupSchedules=(await client.get(base+'/backupSchedules')).body.backupSchedules?.length||0;}catch{checks.firestoreBackupSchedules='not_verified';}
  fs.mkdirSync(path.join(root,'ops'),{recursive:true});fs.writeFileSync(path.join(root,'ops/readiness.json'),JSON.stringify(checks,null,2));console.log(JSON.stringify(checks,null,2));
}
main().catch(()=>{console.error('Readiness check failed; no settings changed.');process.exitCode=1;});
